export const ATTENDANCE_STATE = {
  OPEN: 'OPEN',
  WAITING_IMAGE: 'WAITING_IMAGE',
  IN_ANALYSIS: 'IN_ANALYSIS',
  WAITING_SCHEDULE: 'WAITING_SCHEDULE',
  HUMAN_HANDOFF: 'HUMAN_HANDOFF',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
};

export const ATTENDANCE_MODE = {
  AUTO: 'AUTO',
  MANUAL: 'MANUAL',
};

export const QUOTE_STATUS = {
  DRAFT: 'DRAFT',
  ANALYZED: 'ANALYZED',
  NEEDS_HUMAN: 'NEEDS_HUMAN',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CLOSED: 'CLOSED',
};
